AG_shop/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from Product_shop.views import product_collect_men,product_collect_women,product_collect_kids
from .views import Home_Page,Navigation,Footer,Search,collect_women_nav,collect_men_nav





urlpatterns = [

    path('', Home_Page),
    path('', include("account_shop.urls",namespace='account')),
    path('', include("Product_shop.urls", namespace='product_shop')),
    path('', include("shopping_cart.urls", namespace='shopping_cart')),
    path('', include("sitesetting.urls", namespace='sitesetting')),
    path('', include("comment_product.urls", namespace='comment_product')),
    path('', include("favorite_prducts.urls", namespace='favorite_product')),
    url('collect_women_nav', collect_women_nav, name='women_nav'),
    url('collect_men_nav', collect_men_nav, name='men_nav'),

    path('admin/', admin.site.urls),
    url('partial-view-nav/1hhd23',Navigation,name='Navigation'),
    url(r'^partial-view-fotter/(?P<arg1>\w+)/(?P<arg2>\w+)/$', Footer, name='Footer'),
    url(r'^partial-view-search/(?P<arg1>\w+)/(?P<arg2>\w+)/$', Search, name='Search'),
    url('collect_men',product_collect_men, name='product_collect_men'),
    url('collect_women', product_collect_women, name='product_collect_women'),
    url('collect_kids', product_collect_kids, name='product_collect_kids'),

    #


    # # url(r'^collect_kids_sas', product_collect_kids, name='collect_kids'),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product_shop/urls.py
from django.conf.urls import url
from django.urls import path,include
from Product_shop.views import list_view_women, product_detail, search, \
    list_view_men,collect_product_types_men,collect_product_types_women,\
    collect_product_main_men,collect_product_main_women,collect_product_men,\
    collect_product_women,list_view_kids,collect_product_kids,collect_product_main_kids,collect_product_types_kids

app_name='product_shop'

urlpatterns = [

    #list view ------------------------------------------------------------
    path('list_view/women',list_view_women,name="list_view_women"),
    path('list_view/men', list_view_men, name="list_view_men"),
    path('list_view/kids', list_view_kids, name="list_view_kids"),

    # path('list_view-list-model',product_list_view_list_model.as_view(),name="list_view_list_model"),
    # path('list_view/collect/<category_name>',collect_product_page.as_view(),name="collect_product"),

    # details view ------------------------------------------------------------
    path('list_view/<product_Gender>/<slug>/<productId>', product_detail,name="details_view"),

    # search ------------------------------------------------------------
    path('list_view/search',search.as_view()),

    # collect ------------------------------------------------------------
    path('list_view/men_type/<category_name_type>', collect_product_types_men.as_view(), name="collect_men_type"),
    path('list_view/women_type/<category_name_type>', collect_product_types_women.as_view(), name="collect_women_type"),
    path('list_view/kids_type/<category_name_type>', collect_product_types_kids.as_view(), name="collect_kids_type"),

    path('list_view/men_main/<category_name_type>', collect_product_main_men.as_view(), name="collect_men_main"),
    path('list_view/women_main/<category_name_type>', collect_product_main_women.as_view(), name="collect_women_main"),
    path('list_view/kids_main/<category_name_type>', collect_product_main_kids.as_view(), name="collect_kids_main"),

    path('list_view/men/<category_name_type>', collect_product_men.as_view(), name="collect_men"),
    path('list_view/women/<category_name_type>', collect_product_women.as_view(), name="collect_women"),
    path('list_view/kids/<category_name_type>', collect_product_kids.as_view(), name="collect_kids"),

]

account_shop/urls.py
from django.urls import path,include
from account_shop.views import Log_in,Log_out,Register,Edit_user,forget_pass,forget_pass_reset
from django.contrib.auth import views as auth_views
app_name="account"



urlpatterns = [

    path('Login',Log_in ,name='login'),
    path('Logout',Log_out,name='loginout'),
    path('Register',Register,name='register'),
    path('Edit', Edit_user, name='Edit'),
    path('forget_pass',forget_pass,name='password_reset'),
    path('forget_pass/<uuidcode>',forget_pass_reset,name='forget_reet'),


]

shopping_cart/urls.py
from django.conf.urls import url
from django.urls import path,include
from shopping_cart.views import  make_order,shopping_cart_page,remove_order_detail,shopping_cart_finally_page

app_name='shopping_cart'

urlpatterns = [

    path('makecarts',make_order,name="basket"),
    path('carts',shopping_cart_page,name="carts"),
    path('remove_order/<detail_id>',remove_order_detail,name='remove'),
    path('finallt_carts', shopping_cart_finally_page, name="finallt_carts"),

]

sitesetting/urls.py
from django.conf.urls import url
from django.urls import path,include
from sitesetting.views import contact_us_page,privacy_page,rules_page

app_name='contact_us'

urlpatterns = [


    path('contact_us', contact_us_page, name="contact_us_form"),
    path('privacy_page', privacy_page, name="privacy_page"),
    path('rules_page', rules_page, name="rules_page"),


]

templates/Main_template/Footer.html
{% load static %}

<section class="newsletter-section align-center ptb-100">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-xl-7 col-lg-9 col-12">
                <div class="newsletter-title">
                    <h2 class="main_title">برای خبرنامه ثبت نام کنید </h2>
                    <p>برای دریافت آخرین محصولات تخفیف دار ثبت نام کنید </p>
                </div>
                <div class="newsletter-input">
                    <form method="post">
                         {% csrf_token %}
                        <div class="form-group m-0">
                            {{ register_form }}
                        </div>
                        <button type="submit" class="btn btn-color"><span class="d-none d-sm-block">اشتراک</span> <i class="fa fa-send d-block d-sm-none"></i></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</section>


<footer class="footer-part">
    <div class="container">
        <div class="footer-top ptb-100">
             <div class="mb_-30">
                  <div class="row">
                        <div class="col-12 col-lg-3 col-md-6">
                            <div class="footer-about mb-sm-30">
                                <div class="footer-logo">
                                    <a href="{% static 'index.html' %}">
                                    <img src="{{ site.logo_image.url }}" style="height: 80px" alt="logo">
                                    </a>
                                </div>
                                <p class="footer-p">{{ site.about_office }}</p>
                            </div>
                        </div>

                        <div class="col-12 col-lg-3 col-md-6">
                             <div class="footer-static-block">
                                <span class="opener plus"></span>
                                <h3 class="head-three">اطلاعات</h3>
                                <ul class="footer-menu footer-block-contant">
                                <li><a href="{% url 'contact_us:contact_us_form' %}">تماس با ما</a></li>
                                <li><a href="{% url 'contact_us:rules_page'%}">شرایط و قوانین</a></li>
                                <li><a href="{% url 'contact_us:privacy_page' %}">حریم خصوصی</a></li>
                                </ul>
                              </div>
                        </div>
                        <div class="col-12 col-lg-3 col-md-6">
                             <div class="footer-static-block">
                                     <span class="opener plus"></span>
                                     <h3 class="head-three">خرید</h3>
                                    <ul class="footer-menu footer-block-contant">
                                    <li><a href="{% url 'product_shop:list_view_men' %}">مردانه </a></li>
                                    <li><a href="{% url 'product_shop:list_view_women' %}">زنانه</a></li>
                                    <li><a href="{% url 'product_shop:list_view_kids' %}">بچه گانه</a></li>

                                    </ul>
                             </div>
                        </div>
                        <div class="col-12 col-lg-3 col-md-6">
                            <div class="footer-static-block">
                                <span class="opener plus"></span>
                                 <h3 class="head-three">تماس با ما</h3>
                                  <div class="contact-box footer-block-contant">
                                       <ul>
                                            <li>
                                                <div class="contact-thumb">
                                                    <img src="{% static 'images/address-icon.svg' %}" alt="">
                                                </div>
                                                <div class="contact-box-detail">
                                                    <p>{{ site.address }}</p>
                                                </div>
                                            </li>
                                                <li>
                                                    <div class="contact-thumb">
                                                        <img src="{% static 'images/phone-icon.svg' %}" alt="">
                                                    </div>
                                                        <div class="contact-box-detail">
                                                        <p>{{ site.phone }}</p>
                                                    </div>
                                                </li>
                                            <li>
                                                <div class="contact-thumb">
                                                    <img src="{% static 'images/mail-icon.svg' %}" alt="">
                                                </div>
                                                <div class="contact-box-detail">
                                                    <p><span class="__cf_email__" data-cfemail="1d7e7273697c7e695d746f7c736e69647178336978706d717c6978">{{ site.email }}</span></p>
                                                </div>
                                            </li>
                                       </ul>
                                </div>
                            </div>
                        </div>
                  </div>
            </div>
        </div>
        <div class="footer-bottom align-center">
             <div class="row">
                <div class="col-12">
                    <div class="w-100">
                        <p class="mb-0">{{ site.write_ruls }}</p>
                    </div>
                </div>
                <div class="col-12">
                    <div class="social-media">
                        <ul>
                            <li><a href="{{ site.telegrame_address }}"target="_blank"><i class="fa fa-telegram"></i></a></li>
                            <li><a href="{{ site.twitter_address }}"target="_blank"><i class="fa fa-twitter"></i></a></li>
                            <li><a href="{{ site.instagrame_address }}"target="_blank"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
             </div>
        </div>
    </div>
</footer>

templates/Main_template/Navigation.html
{% load static %}
{% load humanize %}
{% load render_partial %}

{% url 'account:login' as Login %}
{% url 'account:loginout' as Logout %}
{% url 'account:register' as register %}
{% url 'account:Edit' as edit %}
{% url 'product_shop:list_view_women' as Womenlist %}
{% url 'product_shop:list_view_men' as menlist %}
{% url 'shopping_cart:carts' as carts %}
{% url 'shopping_cart:finallt_carts' as finalcarts %}

{% url 'sitesetting:contact_us_form' as contact_us %}
{% url 'product_shop:list_view_kids' as Kidslist %}
{% url 'favorite_product:favorite_page' as favorite %}

<div id="preloader"></div>


<header id="header">
    <div class="container position-r">
        <div class="row m-0">
            <div class="col-lg-3 col-md-4 col-4 p-0">
                <div class="navbar-header">
                    <a class="navbar-brand page-scroll" href="/">
                    <img alt="logo" src="{{ site.logo_image.url }}" style="height:52px"  id="logo_img">
                    </a>
                </div>
            </div>
            <div class="col-lg-9 col-md-8 col-8 p-0 position-initial">
                 <div class="left-side">
                    <button data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle d-block d-lg-none d-xl-none" type="button"><i class="fa fa-bars"></i>
                    </button>
                    <div class="overlay"></div>
                    <div class="header-right-link">
                        <ul>
                            <li class="search-box">
                                 <a href="#"><span></span></a>
                            </li>
                            <li class="account-icon">
                                <a href="#"><span></span></a>
                                <div class="header-link-dropdown account-link-dropdown">
                                    <ul class="link-dropdown-list">
                                        <li> <span class="dropdown-title">خوش آمدید {{ name }}</span>
                                            <ul>
                                               {% if not request.user.is_authenticated %}
                                                     <li><a href="{{ Login }}">ورود اعضا</a></li>
                                                     <li><a href="{{ register }}">ثبت نام</a></li>

                                                {% else %}
                                                     <li><a href="{{ edit }}">ویرایش اطلاعات</a></li>
                                                     <li><a href="{{ Logout }}">خروج</a></li>
                                               {% endif %}
                                            </ul>
                                        </li>
                                        <li> <span class="dropdown-title">سبد خرید</span>
                                            <ul>

                                                     <li class="level3"><a href="{{ carts }}">سبد خرید</a></li>
                                                    <li class="level3"><a href="{{ finalcarts }}">ثبت نهایی</a></li>
                                            </ul>
                                        </li>
                                        <li> <span class="dropdown-title">علاقه مندی ها</span>
                                            <ul>

                                                     <li class="level3"><a href="{{ favorite }}">علاقه مندی ها</a></li>
                                            </ul>
                                        </li>
                                    </ul>
                                </div>
                            </li>
                            <li class="cart-icon">
                            <a href="{{ carts }}"> <span> <small class="cart-notification">{{ len }}</small> </span> </a>
                            <div class="cart-dropdown header-link-dropdown">
                            <ul class="cart-list link-dropdown-list">
                                {% for basket in orderDitails %}
                                     <li>
                            <a href="/remove_order/{{ basket.id }}" class="close-cart"><i class="fa fa-times-circle"></i></a>
                            <figure>
                            <a href="{{ basket.product.get_absolute_url }}" class="pull-right">
                            <img alt="" src="{{ basket.product.product_image.url }}">
                            </a>
                            <figcaption>
                            <span>
                            <a href="{{ basket.product.get_absolute_url }}">{{ basket.product.product_name }}</a>
                            </span>
                                {% if basket.product.product_type == 'discount'%}
                                    <p class="cart-price">{{ basket.product.discount|intcomma:False }} تومان</p>
                                      {% else %}
                                       <p class="cart-price">{{ basket.product.product_price|intcomma:False }} تومان</p>
                                       {% endif %}

                            <div class="product-qty">
                            <label>تعداد</label>
                            <div class="custom-qty">
                            {{ basket.count }}
                            </div>
                            </div>
                            </figcaption>
                            </figure>
                            </li>
                                {% endfor %}
                            </ul>
                            <p class="cart-sub-totle">
                            <span class="pull-right">مبلغ کل</span>
                            <span class="pull-left">
                            <strong class="price-box">{{ total|intcomma:False }} تومان</strong>
                            </span>
                            </p>
                            <div class="clearfix"></div>
                            <div class="mt-20">
                            <a href="{{ carts }}" class="btn-color btn">سبدخرید</a>
                            <a href="{{ finalcarts }}" class="btn-color btn left-side">ثبت نهایی</a>
                            </div>
                            </div>
                            </li>
                        </ul>
                    </div>
                    <div id="menu" class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="level">
                                <a href="/" class="nav-link">خانه</a>
                            </li>
                            <li class="level dropdown">
                                <span class="opener plus"></span>
                                <a href="{{ Womenlist }}" class="nav-link">بانوان</a>
                                {% render_partial 'women_nav' %}
                            </li>
                            <li class="level dropdown">
                                <span class="opener plus"></span>
                                <a href="{{ menlist }}" class="nav-link">آقایان</a>
                                {% render_partial 'men_nav' %}
                            </li>

                            <li class="level">
                                 <a href="{{ Kidslist }}" class="nav-link">بچه گانه</a>
                            </li>
                             <li class="level dropdown">
                                <span class="opener plus"></span>
                                <a href="{{ contact_us }}" class="nav-link">تماس با ما</a>

                            </li>
                            <li class="level dropdown">
{#                                <span class="opener plus"></span>#}
{#                                <a href="{% static 'blog-left-col.html' %}">بلاگ</a>#}
{#                                <div class="megamenu mobile-sub-menu">#}
{#                                    <div class="megamenu-inner-top">#}
{#                                        <ul class="sub-menu-level1">#}
{#                                            <li class="level2 ">#}
{#                                                <ul class="sub-menu-level2">#}
{#                                                    <li class="level3"><a href="{% static 'blog-left-col.html' %}"><span>■</span>بلاگ سایدبار چپ</a></li>#}
{#                                                    <li class="level3"><a href="{% static 'blog-right-col.html' %}"><span>■</span>بلاگ سایدبار راست</a></li>#}
{#                                                    <li class="level3"><a href="{% static 'blog-detail.html' %}"><span>■</span>صفحه خبر</a></li>#}
{#                                                </ul>#}
{#                                            </li>#}
{#                                        </ul>#}
{#                                    </div>#}
{#                                </div>#}
                            </li>

                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>

templates/Main_template/__MAIN_tamplate.html
{% load render_partial %}
{% load static %}
<!DOCTYPE html>
<html dir="rtl" lang="fa-IR">

<head>

    {% block title %}{% endblock %}

    {% include 'Main_template/__header_code_template.html' %}

</head>

<body class="text-right">



     {% with some_var=6 %}

        {% render_partial 'Search'  arg1=36 arg2=some_var %}

    {% endwith %}

<div class="main">



    {% render_partial 'Navigation'  %}



    {% block content %}{% endblock %}

       {% with some_var=4 %}

            {% render_partial 'Footer' arg1=38 arg2=some_var %}

       {% endwith %}

    {% include 'Main_template/__footer_code_template.html' %}




</div>

    {% block javascript %}
    {% endblock javascript %}

</body>
</html>

templates/Main_template/__footer_code_template.html
{% load static %}


<script data-cfasync="false" src="{% static '/cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
<script src="{% static 'js/modernizr.js' %}"></script>

<script>
	    /* ------------ Newslater-popup JS Start ------------- */
	    $(window).on('load', function () {
		setTimeout(function () {
		    jQuery.magnificPopup.open({
			items: {src: '{% static '#newslater-popup' %}'}, type: 'inline'}, 0);
		}, 1000)
	    });
	    /* ------------ Newslater-popup JS End ------------- */
</script>-->

<script>
		$(document).ready(function () {
		    //If your <ul> has the id "glasscase"
		    $('#glasscase').glassCase({
			'thumbsPosition': 'bottom',
			'widthDisplayPerc': 100,
			isDownloadEnabled: false,
			zoomPosition :'left',
		    });
		});
</script>
<script src="{% static 'js/custom.js' %}"></script>

{% block javascript %}{% endblock %}

templates/Main_template/__header_code_template.html
{% load static %}

<meta charset="utf-8">

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<link type="image/x-icon" href="{% static 'images/fav-icon.png' %}" rel="icon">

<link rel="stylesheet" type="text/css" href="{% static 'css/glass-case.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/xpoge.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">

templates/Main_template/__search_templates.html
{#<div id="preloader"></div>#}

<div class="sidebar-search-wrap">
    <div class="sidebar-table-container">
        <div class="sidebar-align-container">
            <div class="search-closer right-side"></div>
            <div class="search-container">
                <form method="get" id="search-form" action="/list_view/search">
                    <input type="text" id="s" class="search-input" name="q" placeholder="جستجو کنید" value="{{ request.GET.q }}">
                </form>
                <span>محصول مورد نظر را جستجو کنید</span>
            </div>
        </div>
    </div>
</div>

<div id="newslater-popup" class="mfp-hide white-popup-block open align-center">
    <div class="nl-popup-main">
        <div class="nl-popup-inner">
            <div class="newsletter-inner">
                <div class="row">
                    <div class="col-md-6"></div>
                    <div class="col-md-6">
                        <div class="mtb-30">
                            <h2 class="main_title">اشتراک محصولات</h2>
                            <span class="sub-title mb-30">ثبت نام کنید و 10٪ تخفیف بگیرید</span>
                            <form>
                                <input type="email" placeholder="ایمیل خود را وارد کنید">
                                <button class="btn-color big-width btn" title="اشتراک">اشتراک</button>
                            </form>
                            <div class="check-box mt-30">
                                <span>
                                    <input type="checkbox" class="checkbox" id="different-address" name="Ship to a different address?">
                                    <label for="different-address">دیگه به من این و نشون نده</label>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>